version: '3'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    deploy:
      mode: global
    ports:
      - 5601:5601
    volumes:
      - /root/kibana.yml:/usr/share/kibana/config/kibana.yml
