---

- yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.0-x86_64.rpm
    state: present

- template:
    src: ./templates/filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- service:
    name: filebeat
    state: stopped

- service:
    name: filebeat
    state: started
    enabled: yes
